### ISSUE TITLE
Fix für Line Breaks für mintinline macht den Blocksatz im Text kaputt

### ISSUE THREAD

**Issue by jones1008** [MasterZydra/DHBW.LaTeX_Template#15]
Mir ist gerade aufgefallen, dass die Zeile `\setlength{\rightskip}{0pt plus 1 fil}` [in der Präambel](https://github.com/MasterZydra/DHBW.LaTeX_Template/blob/master/template/preamble.tex#L188) aus dem commit [88d1306](https://github.com/MasterZydra/DHBW.LaTeX_Template/commit/88d13063c4437c7f7b2f918ac39876a2e3c9e366) den Blocksatz und damit auch die Hyphenation vom normalen Text kaputt macht... 

Wir müssen diesen Befehl entweder irgendwie nur auf `\mintinline`-Befehle beschränken, oder den Umbruch in eine neue Zeile bei `\mintinline` irgendwie anders lösen.

**Comment by jones1008** [comment]
Ich habe eine mögliche Lösung gefunden. Die Zeile `\setlength{\rightskip}{0pt plus 1 fil}` raus und dafür:
```latex
\setmintedinline{
    bgcolor={},
    breakanywhere
}
```
Das deaktiviert allerdings den grauen Hintergrund bei `\mintinline`, aber die Umbrüche funktionieren einigermaßen:
![grafik](https://user-images.githubusercontent.com/25104859/122555210-476df080-d03a-11eb-986c-777a8677822d.png)

Dass `\mintinline` mit bgcolor und breakanywhere nicht funktioniert ist ein bekanntes Problem:
- https://tex.stackexchange.com/questions/419934/breaklines-doesnt-work-with-mintinline
- http://tug.ctan.org/macros/latex/contrib/minted/minted.pdf (Minted Doku unter _5.3 Available Options - bgcolor_ steht was dazu)

@MasterZydra: Was meinst du dazu? Soll das so mit rein? Ist auf jeden Fall ne bessere Lösung, als den Blocksatz vom gesamten Dokument kaputt zu machen

**Comment by MasterZydra** [comment]
Blocksatz sollte auf alle Fälle erhalten bleiben.

Wenn ich deinen Vorschlag auf 
```latex
\setmintedinline{
    bgcolor=codebg,
    breakanywhere
}
```
ändere, kommt dieser Bug zustande, dass die Farbe gesetzt wird und der Zeilenumbruch wieder kaputt ist.

Ich tendiere lieber den automatischen Zeilenumbruch rauszunehmen und das Highlighting zu erhalten. Dann muss man da halt manuell drüber schauen und ggf. einen Zeilenumbruch `\\` einfügen.

Ohne das Highlighting ist der Quellcode nur schwer vom normalen Text zu unterscheiden.

@jones1008 Wofür bist du?

**Comment by MasterZydra** [comment]
Würde den Hinweis entsprechend mit in das Beispiel ergänzen mit der Begründung, dass dies ein bekannter Bug ist.

**Comment by jones1008** [comment]
ich habe jetzt nochmal rumprobiert den Linebreak mit Hintergrundfarbe hinzukriegen mit irgendwelchen Workarounds, aber leider ohne Erfolg :/

Am vielversprechendsten sah eigentlich das hier aus: https://tex.stackexchange.com/a/312583/241332

Allerdings wirft der Latex-Compiler immer einen Fehler, wenn man das mit `\mintinline{}{}` verwendet...

Dann hätte ich gesagt, wir nehmen den automatischen Zeilenumbruch raus und man muss am Ende manuell drüber schauen und newlines `\\` einfügen

**Comment by MasterZydra** [comment]
Schade, dass dieser Fehler noch nicht behoben wurde. Dann werde ich den automatischen Zeilenumbruch wieder entfernen und das Ganze entsprechend in den Beispielen anmerken.
