### ISSUE TITLE
Change examples for citation

### ISSUE THREAD

**Issue by jones1008** [MasterZydra/DHBW.LaTeX_Template#17]
[In `chap2_examples.tex`](https://github.com/MasterZydra/DHBW.LaTeX_Template/blob/983dba2cc3ec1628574772eced8f526a007ae61a/chapters/chap2_examples.tex#L156) the citation with page reference is explained like that:
```latex
Angabe von Seitenzahl für die Quelle \cite[S. 5ff]{Nobody07}
```

I just learned [here](https://de.wikibooks.org/wiki/LaTeX-Kompendium:_Zitieren_mit_BibTeX#Literaturtypen_(Entry_types)) that you can just write
`\cite[12]{<cite_name>}` for citation with one page reference and `\cite[12\psq]{<cite_name>}` for citation with reference to two pages and `\cite[12\psqq]{<cite_name>}` for citation with reference to more than two pages.

I think we should write that in the `chap2_examples.tex`

**Comment by MasterZydra** [comment]
Nice to know.
I will add it as further examples. So the user can decide himself what variant he wants to use.
