### ISSUE TITLE
Space after code block on the end of the page

### ISSUE THREAD

**Issue by jones1008** [MasterZydra/DHBW.LaTeX_Template#18]
The `code` environment that is specified [here](https://github.com/MasterZydra/DHBW.LaTeX_Template/blob/983dba2cc3ec1628574772eced8f526a007ae61a/template/preamble.tex#L170) creates an unnecessary space/newline if the code block is placed at the end of the page:

<img src="https://user-images.githubusercontent.com/25104859/123244354-239c2600-d4e4-11eb-8e28-552f16f08d7a.png" width="600">

<hr>

I then noticed that there is a `\\` [at the end of the `code` definition](https://github.com/MasterZydra/DHBW.LaTeX_Template/blob/983dba2cc3ec1628574772eced8f526a007ae61a/template/preamble.tex#L184). Removing this newline `\\` fixes this issue:

<img src="https://user-images.githubusercontent.com/25104859/123244688-707ffc80-d4e4-11eb-9a36-8b912fba16ad.png" width="600">

**Comment by MasterZydra** [comment]
Thanks @jones1008. Is fixed now.
