### ISSUE TITLE
Use none serif font in caption of images, tables, ...

### ISSUE THREAD

**Issue by MasterZydra** [MasterZydra/DHBW.LaTeX_Template#20]
- [x] Research how to change the font in the captions.
- [x] Than decide which style to use in the template.

**Comment by MasterZydra** [comment]
**Before**:
![image](https://user-images.githubusercontent.com/44842054/124767945-8821a100-df38-11eb-81f7-7471d9f7e565.png)
![image](https://user-images.githubusercontent.com/44842054/124768081-a9828d00-df38-11eb-9afa-b4e5b15add89.png)

**Comment by MasterZydra** [comment]
**After**
![image](https://user-images.githubusercontent.com/44842054/124770091-527db780-df3a-11eb-8310-a7b9a1f426e8.png)
![image](https://user-images.githubusercontent.com/44842054/124770126-5c071f80-df3a-11eb-95b0-9cb461e64dc8.png)

```LaTeX
\usepackage[
    font =      {footnotesize, sf},
    labelfont = {footnotesize, bf}
]{caption}
```

**Comment by MasterZydra** [comment]
I think the new optic is quit nice and would use it.

@jones1008 What do you think?
We have a lot of options e.g. write "Code 2.1" in normal font (without bold).
Dokumentation: https://ftp.tu-chemnitz.de/pub/tex/macros/latex/contrib/caption/caption-deu.pdf

**Comment by jones1008** [comment]
yes, I think the new one looks better... I also like that the caption isn't blue anymore, since this might make you think that you can click on it as a link
